### ISSUE TITLE
Enhanced fluent binding syntax

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#116]
## Expected Behavior

More helpers should be available in `IBindingInWhenProxySyntax <T>`. Some helper suggestions:

```
interface IBindingInWhenProxySyntax<T> {

    // already implemented
    inTransientScope(): IBindingInWhenProxySyntax<T>;
    inSingletonScope(): IBindingInWhenProxySyntax<T>;
    when(constraint: (request: IRequest) => boolean): IBindingInWhenProxySyntax<T>;
    whenTargetNamed(name: string): IBindingInWhenProxySyntax<T>;
    whenTargetTagged(tag: string, value: any): IBindingInWhenProxySyntax<T>;
    onActivation(fn: (context: IContext, injectable: T) => T): IBindingInWhenProxySyntax<T>;

    // NEW!
    whenInjectedInto(parent: (Function|string)): IBindingOnSyntax<T>;
    whenParentNamed(name: string): IBindingOnSyntax<T>;
    whenParentTagged(tag: string, value: any): IBindingOnSyntax<T>;
    whenAnyAncestorIs(ancestor: (Function|string)): IBindingOnSyntax<T>;
    whenNoAncestorIs(ancestor: (Function|string)): IBindingOnSyntax<T>;
    whenAnyAncestorNamed(name: string): IBindingOnSyntax<T>;
    whenAnyAncestorTagged(tag: string, value: any): IBindingOnSyntax<T>;
    whenNoAncestorNamed(name: string): IBindingOnSyntax<T>;
    whenNoAncestorTagged(tag: string, value: any): IBindingOnSyntax<T>;
    whenAnyAncestorMatches(constraint: (request: IRequest) => boolean): IBindingOnSyntax<T>;
    whenNoAncestorMatches(constraint: (request: IRequest) => boolean): IBindingOnSyntax<T>;
}
```
## Current Behavior

The [current `IBindingInWhenProxySyntax <T>`](https://github.com/inversify/InversifyJS/blob/master/src/interfaces/syntax/binding_in_when_proxy_syntax.d.ts) only supports `when`, `whenTargetNamed` and `whenTargetTagged`:

```
interface IBindingInWhenProxySyntax<T> {
    inTransientScope(): IBindingInWhenProxySyntax<T>;
    inSingletonScope(): IBindingInWhenProxySyntax<T>;
    when(constraint: (request: IRequest) => boolean): IBindingInWhenProxySyntax<T>;
    whenTargetNamed(name: string): IBindingInWhenProxySyntax<T>;
    whenTargetTagged(tag: string, value: any): IBindingInWhenProxySyntax<T>;
    onActivation(fn: (injectable: T) => T): IBindingInWhenProxySyntax<T>;
}
```
## Tasks
- [x]  `whenInjectedInto(parent: Type): IBindingInWhenProxySyntax<T>;`
- [x]  `whenInjectedInto(parent: string): IBindingInWhenProxySyntax<T>;`
- [x]  `whenParentNamed(name: string): IBindingInWhenProxySyntax<T>;`
- [x]  `whenParentTagged(key: string, value: any): IBindingInWhenProxySyntax<T>;`
- [x]  `whenAnyAncestorIs(ancestor: (Function|string)): IBindingOnSyntax<T>;`
- [x]  `whenNoAncestorIs(ancestor: (Function|string)): IBindingOnSyntax<T>;`
- [x]  `whenAnyAncestorNamed(name: string): IBindingInWhenProxySyntax<T>;`
- [x]  `whenNoAncestorNamed(string name): IBindingInWhenProxySyntax<T>;`
- [x]  `whenAnyAncestorTagged(key: string, value: any): IBindingInWhenProxySyntax<T>;`
- [x]  `whenNoAncestorTagged((key: string, value: any): IBindingInWhenProxySyntax<T>;`
- [x]  `whenAnyAncestorMatches((request) => boolean): IBindingInWhenProxySyntax<T>;`
- [x]  `whenNoAncestorMatches((request) => boolean): IBindingInWhenProxySyntax<T>;`
- [x]  Remove `inTransientScope()` (is the default so it is not needed)
- [x]  Refactor `IBindingInWhenProxySyntax` into multiple classes
- [x]  Implement `IBindingInSyntax`
- [x]  Implement `IBindingWhenSyntax`
- [x]  Implement `IBindingOnSyntax`
- [x]  Prevent config errors via fluent syntax

**Comment by remojansen** [comment]
This is not ready but looking good :smile: 

![rutovtwivo](https://cloud.githubusercontent.com/assets/10656223/13901820/847ff22e-ee28-11e5-81e6-ee42986bf29f.gif)
