### ISSUE TITLE
2.0.0 Release

### ISSUE THREAD

**Issue by remojansen** [inversify/InversifyJS#256]
I'm creating this issue to keep track of everything that I need to do for the 2.0.0 release :tada:
- [x] #269 dts 1.0.7 'file not found' 
- [x] #262 Confusing issue with resolving class if module is called from separate module
- [x] #266 Property injection with multiple tests in seperate files
- [x] #267 TypeError: Cannot convert a Symbol value to a string
- [x] Upgrade inversify-logger-middleware to beta.10
- [x] Release inversify-logger-middleware 1.0.0-beta.6
- [x] Upgrade inversify-binding-decorators to beta.10
- [x] Release inversify-binding-decorators 1.0.0-beta.6
- [x] Upgrade inversify-express-utils to beta.10
- [x] Release inversify-express-utils 1.0.0-beta.2
- [x] Revision inversify-dts [code review](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9742#discussion-diff-67943749)
- [x] Update inversify-dts to match everything above
- [x] Release inversify-dts 1.0.8
- [x] Release inversify@2.0.0-rc.1
- [x] #234 2.0.0 Website
- [x] #310 Rewrite property inject so it becomes not aware of kernel instances
- [x] #330 typings not included in the package
- [x] #362 Migrate all side projects to TypeScript 2.0

**Comment by Offirmo** [comment]
:+1: can't wait for the 2.0.0 release. I'll write a blog post.

**Comment by remojansen** [comment]
@Offirmo thanks! We are right now block by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10998 and the TypeScript 2.0 release but it should be here soon :smile:

**Comment by remojansen** [comment]
InversifyJS is now ready for a new release RC.14 :tada: after that I have to [migrate all side projects to TypeScript 2.0](https://github.com/inversify/InversifyJS/issues/362). At that point, RC.14 will be promoted to 2.0 stable.

**Comment by remojansen** [comment]
<img width="520" alt="screen shot 2016-09-11 at 09 12 15" src="https://cloud.githubusercontent.com/assets/10656223/18416054/3a167c50-7800-11e6-83e3-22fe886e6449.png">

🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

Thanks a lot guys for all the work during all this months!
