### ISSUE TITLE
Update side projects

### ISSUE THREAD

**Issue by lholznagel** [inversify/InversifyJS#403]
Like discussed in gitter, the side projects need to be updated to the inversify 3.0.0-beta.1
```
Lars Holznagel @lholznagel Nov. 05 19:03
Hey @remojansen I just updated one of my repos to the new beta. Should we also update things like inversify-express-example to the new version or wait until it is final?

Remo H. Jansen @remojansen Nov. 08 18:22
Hi @lholznagel you can update them if you want 
```

## Projects to update
- [x] inversify/inversify-vanillajs-helpers#1
- [x] inversify/inversify-restify-utils#15
- [x] inversify/inversify-express-utils#19
- [ ] [inject-decorators](https://github.com/inversify/inversify-inject-decorators)
- [ ] [logger-middleware](https://github.com/inversify/inversify-logger-middleware)
- [x] inversify/inversify-binding-decorators#31

## Examples to update
- [ ] [basic-example](https://github.com/inversify/inversify-basic-example)
- [ ] [express-example](https://github.com/inversify/inversify-express-example)

**Comment by remojansen** [comment]
Hi @lholznagel I'm closing this because this issue is now outdated... I will create a new one in a few minutes.

**Comment by lholznagel** [comment]
Jop, just saw it
